Withdraw_time = None
User_id = None
FORCED_SEGMENT = 0
user_data_points = 0
total_win_today = 0
history_json = {}
restrict = False
message = ""
message_time=""
base_server_ts = None
base_local_ts  = None